# ArgoCD Application for Currency Converter
# This file defines how ArgoCD should deploy and manage the Currency Converter application

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: currency-converter
  namespace: argocd
  labels:
    app.kubernetes.io/name: currency-converter
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project to which this application belongs
  project: default
  
  # Source configuration - where to find the application manifests
  source:
    # Git repository URL
    repoURL: https://github.com/singhavinash2915/avinash-cognyte-devops-test.git
    
    # Git branch or tag to track
    targetRevision: main
    
    # Path within the repository where Helm chart is located
    path: helm/currency-converter
    
    # Helm configuration
    helm:
      # Override default values
      valueFiles:
        - values.yaml
      
      # Additional Helm parameters
      parameters:
        - name: image.tag
          value: latest
        - name: replicaCount
          value: "1"
        - name: service.type
          value: ClusterIP
  
  # Destination configuration - where to deploy the application
  destination:
    # Kubernetes server URL (use in-cluster server)
    server: https://kubernetes.default.svc
    
    # Target namespace
    namespace: currency-converter
  
  # Sync policy configuration
  syncPolicy:
    # Automatically create namespace if it doesn't exist
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - PrunePropagationPolicy=foreground
    
    # Automatic sync configuration
    automated:
      # Enable automatic sync when changes are detected
      prune: true
      
      # Enable self-healing to revert manual changes
      selfHeal: true
      
      # Allow empty directories to be synced
      allowEmpty: false
    
    # Retry configuration for failed syncs
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  # Health check configuration
  # ArgoCD will consider the application healthy based on these checks
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
  
  # Revision history limit
  revisionHistoryLimit: 10